## Creating a numpy array


when you try to create np array, you should provide a list, hence:
```python
a = np.array(1,2,3,4)    # WRONG'
a = np.array([1,2,3,4])  # RIGHT '
```

### shape, reshape, ndim, axis

```
a=np.random.randint(low=1, high=4,size=[2,3])
print("a:\n",a)
print("a ndim is: ",a.ndim)
print("a shape is: ",a.shape)
```
which gives us:

```
a:
 [[2 2 1]
 [1 1 2]]
a ndim is:  2
a shape is:  (2, 3)
```


```python

         axis 1  --------------------------------►
axis 0 | row 0,col 0 | col 1 | col 2  |        |
 |     +-------------+-------+--------+--------+
 |     | row 0       |       |        |        |
 |     +-------------+-------+--------+--------+
 |     | row 1       |       |        |        |
 ▼     +-------------+-------+--------+--------+
```


```
print("sum of matrix, column wise: ",np.sum(a,axis=0))
print("sum of matrix, row wise:  ",np.sum(a,axis=1))
```
which gives us:

```
print("sum of matrix, column wise: ",np.sum(a,axis=0))
print("sum of matrix, row wise:  ",np.sum(a,axis=1))
```

### missing second dimension

 when we refer to an array missing a second dimension, we're generally talking about a one-dimensional array, often known as a 1D array or a vector. In other words, this is an array that has only one axis. 

Here's what it means:

1. **Shape**: If you query the shape of a 1D array, you'll get something like `(n,)` where `n` is the number of elements. The missing second dimension is evident by the single comma. For a 2D array, the shape would look like `(m, n)`.

2. **Accessing Elements**: For a 1D array, you only need one index to access its elements: `array[i]`. In contrast, for a 2D array, you'd use two indices: `array[i, j]`.

3. **Visualization**: You can think of a 1D array as a simple list or a linear set of items. A 2D array can be visualized as a grid or a matrix.

Example of a 1D array:

```python
array = np.arange(3)
print(array.shape)
print(array.tolist())
print(array.reshape(3,1).tolist())
```
Output: 
```
(3,)
[0, 1, 2]
[[0], [1], [2]]
```
It's worth noting that a 1D array is different from a 2D row or column vector. A column vector has a shape like `(n, 1)`, while a row vector has a shape like `(1, n)`. However, a 1D array's shape will just be `(n,)`.


### ravel

Return a contiguous flattened array. A copy is made only if needed.
```
x=np.array([[2,4,1],[7,2,3]])
# 'C' means c style, row major
# 'F' means fortran style, column major
print("x:\n",x)
print("x.ravel(order='C'):",x.ravel(order='C'))
print("x.ravel(order='F'):",x.ravel(order='F'))
```
outputs:

```
x:
 [[2 4 1]
 [7 2 3]]
x.ravel(order='C'): [2 4 1 7 2 3]
x.ravel(order='F'): [2 7 4 2 1 3]
```



### Flattern

Return a copy of the array collapsed into one dimension
```
print(x.flatten(order='F'))
```

### Reshape
```
print(x.reshape((6,1),order='C'))
```

### Squeez

This function removes one-dimensional entry from the shape of the given array.

```
x=np.random.randint(5 ,size=(1,3,2))
print("x.shape:",x.shape)
print("x.squeeze().shape:",x.squeeze().shape)
```

outputs:
```
x.shape: (1, 3, 2)
x.squeeze().shape: (3, 2)
```



### concatenate, vstack, hstack
```
mat1=np.array(np.random.randint(low=1, high=10,size=[3,4]))
mat2=np.array(np.random.randint(low=1, high=10,size=[3,4]))
print("mat1 is:\n",mat1)
print("mat2 is:\n",mat2)
print("hstack :\n ", np.hstack((mat1,mat2)))
print("concatenate axis=0:\n", np.concatenate((mat1,mat2),axis=0))

print("vstack :\n", np.vstack((mat1,mat2)))
print("concatenate axis=1:\n", np.concatenate((mat1,mat2),axis=1))


print("dstack, shape:\n", np.dstack((mat1,mat2)), "\n", np.dstack((mat1,mat2)).shape  )
print("np.dstack((mat1,mat2))[0,0]:\n",np.dstack((mat1,mat2))[0,0])


print("mat1 flatten:",mat1.flatten())
```



# Random sampling 

```python
print("List of supported distributions:", 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'exponential'
      , 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal',
      'logseries', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f',
      'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'randint',
      'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy',
      'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'triangular', 'uniform', 'vonmises',
      'wald', 'weibull', 'zipf',)
```

Refs: [1](https://docs.scipy.org/doc/np-1.14.0/reference/routines.random.html)


### uniform sampling

```python
dim1=2
dim2=3
dimn=1
print("random values in shape of dim1={}, dim2={}, dimn={} with uniform distribution over [0, 1)".format(dim1, dim2, dimn))
print(np.random.rand(dim1,dim2,dimn))


low=1
high=10
size=4
print("{} random integers of type, between low={} and high={}, inclusive with uniform distribution".format(size,low, high))
print(np.random.randint(low,high,size))
```

### multivariate normal

```
mean = [0, 0]
cov = [[1, 0], [0, 100]]
size=4
print("Draw random {} samples from a multivariate normal distribution with mean={} and cov={}".format(size,mean, cov))
print(np.random.multivariate_normal(mean,cov,size))
```

# Matrix Multiplication
```
x=np.array([[2,1,1],[3,1,4]] )
y=np.random.randint(low=-1,high=4,size=[3,1])
```

so x and y are:
```
x: 
[[2 1 1]
 [3 1 4]]
 
y: 
[[2]
 [3]
 [0]]
```


1. `@` operator: calls the array's `__matmul__` method
2. `dot`: For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors
 (without complex conjugation). 
``` 
print("x@y:\n",x@y)
print("np.matmul(x,y):\n",np.matmul(x,y) )
print("np.dot(x,y): \n",np.dot(x,y) )
```
which gives you 

```python
x@y:
 [[ 5]
 [11]]
matmul(x,y):
 [[ 5]
 [11]]
dot(x,y): 
 [[ 5]
 [11]]
```
For `N` dimensions it is a sum product over the last axis of a and the second-to-last of b

```
a = np.random.rand(8,13,13)
b = np.random.rand(8,13,13)
print(np.dot(a,b).shape )
print(np.matmul(a,b).shape )
```

### View, Copy 
copy is a new array, and the view is just a view of the original array.
 view does not own the data and any changes made to the view will affect the original array, and any changes
 made to the original array will affect the view.
```
x=np.array ([1,2,3,4,5])
y=x.view()
z=x.copy()

x[0]=-1
print("x:", x)
print("y:", y)
print("z:", z)
print(x.base)
print(y.base)
print(z.base)
```

### Broadcasting
broadcasting describes how np treats arrays with different shapes during arithmetic operations.
```
arr = np.arange(12).reshape(3,4)
col_vector = np.array([5,6,7])
```
now how do we add the vector to the array? 

```
#       arr         + col_vector

# [[ 0  1  2  3]     | 5  | 
#  [ 4  5  6  7]   + | 6  | = ?
#  [ 8  9 10 11]]    | 7  |
```

1. First solution, using loops:
```
num_cols = arr.shape[1]

for col in range(num_cols):
	arr[:, col] += col_vector

```

2. Second solution: column-stacking approach turning the col_vector into an array:

```
[[ 0  1  2  3]       [[5 5 5 5]
[4  5  6  7]     +   [6 6 6 6]
[8  9 10 11]]        [7 7 7 7]]
```

```
arr = np.arange(12).reshape(3,4)
add_matrix = np.array([col_vector,] * num_cols).T

arr += add_matrix
```


3. Third solution: Broadcasting
broadcasting allows operations to be performed on arrays of different shapes. Broadcasting automatically expands the smaller array's shape to match the larger array's shape so that they have compatible shapes for element-wise operations. It's a powerful feature that allows for efficient operations without actually copying any data.

Here's an example to illustrate broadcasting:

### Broadcasting a Scalar to a 2D Array:

```python
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar (broadcasting the scalar to each element)
result = arr + 10

print(result)
# Output:
# [[11 12 13]
#  [14 15 16]
#  [17 18 19]]
```

Here, the scalar `10` is broadcasted to each element of the `arr`.

### Broadcasting a 1D Array to a 2D Array:

```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create a 1D array
arr_1d = np.array([1, 0, 1])

# Add the 1D array to each row of the 2D array
result = arr_2d + arr_1d

print(result)
# Output:
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]]
```

In this example, `arr_1d` is broadcasted to each row of `arr_2d`.

**Note**: Broadcasting has rules regarding the compatibility of shapes. For example, dimensions are considered compatible when:

- They are equal, or
- One of them is 1.

If these conditions are not met, a `ValueError` is raised, indicating that the arrays have incompatible shapes for the operation.


### np.vectorize
 `np.vectorize` is a class that converts an ordinary Python function, which accepts scalars and returns scalars, into a "vectorized" function that can operate on (and return) entire arrays. It provides a way to apply the function element-wise on input arrays.

However, it's worth noting that `np.vectorize` doesn't make your code inherently faster. Under the hood, it essentially uses a loop to apply the given function to each element in the input arrays. The primary purpose of `np.vectorize` is to transform a scalar function into one that can operate on and return arrays, making the code cleaner and more in line with NumPy's broadcasting semantics.

### Basic Usage:

```python
import numpy as np

def scalar_function(x):
    return x * x

vectorized_function = np.vectorize(scalar_function)

# Using the vectorized function on an array
arr = np.array([1, 2, 3, 4, 5])
print(vectorized_function(arr))
# Output: [ 1  4  9 16 25]
```

### With Multiple Input Arrays:

The vectorized function can also handle multiple input arrays:

```python
import numpy as np

def scalar_add(x, y):
    return x + y

vectorized_add = np.vectorize(scalar_add)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(vectorized_add(arr1, arr2))
# Output: [5 7 9]
```

### When to Use:

1. **Function Transformation**: As mentioned, the primary purpose is to convert a scalar function into one that works with arrays.
2. **Readability**: It can make the code cleaner when working with NumPy arrays.

### When Not to Use:

1. **Performance**: If you're looking for performance gains, it's usually better to use native NumPy functions or operations that inherently support array computations, as they are implemented in optimized C or Fortran code.
2. **Complex Operations**: For more complicated operations where performance is critical, consider using NumPy's built-in functions or other optimized tools such as `numba` or Cython.

In essence, `np.vectorize` is a convenience function, but if performance is a concern, it's essential to be aware of its loop-like nature under the hood.



### Lambda functions

Lambda functions are anonymous functions defined using the `lambda` keyword in Python. They can be used in tandem with functions like `np.apply_along_axis()` to apply operations element-wise or along a specified axis of a NumPy array.

Here are a couple of examples demonstrating the use of lambda functions with NumPy arrays:

### 1. Applying a Lambda Function Element-wise to a 1D Array:

```python
import numpy as np

# Create a simple 1D array
arr = np.array([1, 2, 3, 4, 5])

# Use lambda to square each element
squared = np.vectorize(lambda x: x**2)(arr)

print(squared)  # Output: [ 1  4  9 16 25]
```

In this example, we use `np.vectorize()` to vectorize the lambda function, allowing it to operate on each element of the array.

### 2. Applying a Lambda Function Along an Axis of a 2D Array:

```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Use lambda to compute the sum of each row
row_sum = np.apply_along_axis(lambda x: np.sum(x), axis=1, arr=arr_2d)

print(row_sum)  # Output: [ 6 15 24]
```

In this example, `np.apply_along_axis()` applies the lambda function (which computes the sum) along `axis=1`, thus computing the sum for each row.

Remember, while lambda functions offer a concise way to define simple functions, they might make the code less readable if the operations are complex. In such cases, it might be better to define a standalone function instead of using lambda.

### operation on numpy arrays

```
x=np.arange(5)
selected_index=[True,True,False, True,False]
print(x[selected_index])

y=x>3
print(y)
print(x[y])
```



### Random Generator

- `np.random.default_rng()`: This is the primary function for creating a Generator instance.  

In [12]:
import numpy as np

rng = np.random.default_rng(seed=42) 

- `np.random.random()`: Generates random floating-point numbers in the half-open interval [0.0, 1.0).

In [4]:

low = -2
high = 5
x = low + (high-low)*np.random.random(size=[5])
print(x)

[1.85212825 1.67633703 4.31313795 4.44694286 0.65558326]


- `np.random.randint`: Generates random integers from a given range.

In [9]:
np.random.randint(low=5,high=20,size=5)
print(x)

[1.85212825 1.67633703 4.31313795 4.44694286 0.65558326]


- np.random.normal(): Generates random numbers from a normal (Gaussian) distribution.

In [13]:
import numpy as np

# Create a Generator object
rng = np.random.default_rng(seed=42)  # Seed for reproducibility

# Generate random floats between 0 and 1
random_floats = rng.random(size=5)
print("Random floats:", random_floats)

# Generate random integers between 1 and 10 (inclusive)
random_integers = rng.integers(low=1, high=11, size=5)
print("Random integers:", random_integers)

# Generate random numbers from a normal distribution (mean=0, stddev=1)
normal_distribution = rng.normal(size=5)
print("Normal distribution:", normal_distribution)

# Generate random numbers from a uniform distribution (0 to 10)
uniform_distribution = rng.uniform(low=0, high=10, size=5)
print("Uniform distribution:", uniform_distribution)

# Generate a random choice from a list
choices = ['apple', 'banana', 'cherry', 'date']
random_choice = rng.choice(choices)
print("Random choice:", random_choice)

# Generate a random array of choices
random_choices = rng.choice(choices, size=3)
print("Random choices array:", random_choices)

# Shuffle an array in-place
my_array = np.array([1, 2, 3, 4, 5])
rng.shuffle(my_array)
print("Shuffled array:", my_array)

#Generate a 2D array of random integers
random_2d_integers = rng.integers(low=0, high=10, size=(3, 4))
print("2D array of random integers:\n", random_2d_integers)

#Generating a random boolean array
random_booleans = rng.random(size=5) < 0.5 # True if less than 0.5
print("Random booleans:", random_booleans)

Random floats: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Random integers: [ 6 10  8  8  8]
Normal distribution: [-0.01680116 -0.85304393  0.87939797  0.77779194  0.0660307 ]
Uniform distribution: [8.22761613 4.43414199 2.27238722 5.54584787 0.63817256]
Random choice: date
Random choices array: ['date' 'date' 'banana']
Shuffled array: [5 4 3 2 1]
2D array of random integers:
 [[9 4 8 6]
 [7 7 1 3]
 [4 4 0 5]]
Random booleans: [False False False  True  True]


### numpy.where()
`numpy.where()` and its lambda equivalents: `numpy.where()` is a powerful function in NumPy that allows you to conditionally select elements from arrays. It's like a vectorized "if-else" statement.

**Basic Usage and Explanation**

The fundamental syntax is:

```python
import numpy as np

condition = np.array([True, False, True, False])
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

result = np.where(condition, x, y)
print(result)  # Output: [ 1 20  3 40]
```

*   `condition`: A boolean array.  Elements where the condition is `True` will be taken from `x`.
*   `x`: The array from which elements are taken if the condition is `True`.
*   `y`: The array from which elements are taken if the condition is `False`.

The output `result` is a new array where each element is chosen based on the corresponding value in the `condition` array.

**Lambda Equivalents**

While `numpy.where()` is highly optimized, you can achieve similar (though often less efficient) results using Python's `lambda` functions and list comprehensions or `zip`.  However, these methods don't provide the same performance benefits as `numpy.where()`, especially for large arrays.

**1. List Comprehension with `zip`:**

```python
result_lambda = np.array([x_val if cond else y_val for cond, x_val, y_val in zip(condition, x, y)])
print(result_lambda) # Output: [ 1 20  3 40] (same result)
```

This is the most direct equivalent using a list comprehension.  `zip` combines the three arrays element-wise, and the `if/else` within the list comprehension selects the correct value.  We then convert the list to a NumPy array.

**2.  `lambda` with `zip` (Less Common and Less Efficient):**

```python
selector = lambda cond, x_val, y_val: x_val if cond else y_val
result_lambda_lambda = np.array([selector(cond, x_val, y_val) for cond, x_val, y_val in zip(condition, x, y)])
print(result_lambda_lambda) # Output: [ 1 20  3 40] (same result)
```

This introduces a `lambda` function, but it doesn't really add anything and is generally less readable than the list comprehension approach.  It's still iterating element-wise.

**3. Nested `np.where` for More Complex Conditions:**

```python
condition1 = np.array([True, False, True, False])
condition2 = np.array([False, True, True, False])

result_nested = np.where(condition1, np.where(condition2, 5, 6), np.where(condition2, 7, 8))
print(result_nested) # Output: [6 7 5 8]

# Equivalent lambda (much less readable and efficient):
result_nested_lambda = np.array([
    5 if cond1 and cond2 else 6 if cond1 else 7 if cond2 else 8
    for cond1, cond2 in zip(condition1, condition2)
])
print(result_nested_lambda) # Output: [6 7 5 8]
```

Nested `np.where()` calls allow for more complex logic. The lambda equivalent rapidly becomes hard to read and maintain.  This is a strong case for using `np.where()`.

**Key Differences and Why `numpy.where()` is Preferred:**

*   **Performance:** `numpy.where()` is significantly faster, especially for larger arrays. It's implemented in C and optimized for vectorized operations. The lambda/list comprehension approaches involve Python loops, which are much slower.
*   **Readability:**  While simple `if/else` conditions can be expressed reasonably well with list comprehensions, `numpy.where()` becomes much clearer for complex nested conditions.
*   **Conciseness:** `numpy.where()` is often more concise, especially for complex conditions.

**When to Use Lambda/List Comprehension:**

You might consider lambda/list comprehension for very small arrays or when the logic is extremely simple and readability is paramount.  However, for any serious numerical work with NumPy, `numpy.where()` is almost always the right choice.  It's more efficient, readable, and idiomatic NumPy.

## Applying a lambda function to NumPy array 
You can apply a lambda function to NumPy array elements in several ways, each with its own performance characteristics and use cases. Here's a breakdown of the common methods and when to use them:

**1. Using `numpy.vectorize()` (Generally Avoid):**

While `np.vectorize()` *appears* to be a concise way to apply a function element-wise, it's often the *slowest* option.  It's essentially a Python loop under the hood, negating the benefits of NumPy's vectorized operations.  Avoid it for performance-sensitive code.

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Example using vectorize (generally avoid)
vfunc = np.vectorize(lambda x: x * 2)
result = vfunc(arr)
print(result)  # Output: [ 2  4  6  8 10]

# Or directly (still slow)
result = np.vectorize(lambda x: x * 2)(arr)
print(result) # Output: [ 2  4  6  8 10]
```

**2. Vectorized Operations (The Preferred Way):**

NumPy excels at vectorized operations.  If your lambda function can be expressed using NumPy's built-in functions and operators, this is the *fastest* and most efficient approach.

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Example using vectorized operation (fastest)
result = arr * 2  # Equivalent to lambda x: x * 2
print(result)  # Output: [ 2  4  6  8 10]

# More complex example:
result = np.where(arr > 2, arr * 2, arr / 2) # Equivalent to a lambda with a conditional
print(result) # Output: [0.5 1.  3.  4.  5. ]

# Another Example:
result = np.sin(arr) # Applying a trigonometric function.
print(result)
```

**3. List Comprehension (Intermediate Speed):**

If your lambda function is too complex to be directly vectorized but you still want some performance improvement over `np.vectorize()`, you can use list comprehension and then convert back to a NumPy array. This is often faster than `np.vectorize()` but slower than direct vectorized operations.

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Example using list comprehension (intermediate speed)
result = np.array([lambda x: x * 2 for x in arr]) # Incorrect: This creates an array of functions!
print(result)

result = np.array([x * 2 for x in arr]) # Correct: This applies the function and creates the array.
print(result)  # Output: [ 2  4  6  8 10]

# More complex example:
result = np.array([x*2 if x>2 else x/2 for x in arr])
print(result) # Output: [0.5 1.  3.  4.  5. ]
```

**4. `numpy.apply_along_axis()` (For Specific Cases):**

`apply_along_axis()` is useful when you need to apply a function to 1D slices of a multi-dimensional array.  It's not as efficient as direct vectorized operations but can be helpful for certain types of operations.

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Example using apply_along_axis (for multi-dimensional arrays)
result = np.apply_along_axis(lambda x: x * 2, axis=0, arr=arr)  # Apply along columns (axis=0)
print(result)
# [[ 2  4  6]
#  [ 8 10 12]]

result = np.apply_along_axis(lambda x: x * 2, axis=1, arr=arr)  # Apply along rows (axis=1)
print(result)
# [[ 2  4  6]
#  [ 8 10 12]]
```

**Key Recommendations:**

* **Prioritize Vectorization:**  Always try to express your operations using NumPy's built-in functions and operators. This is the most efficient approach.
* **Avoid `np.vectorize()`:**  It's often slow and should be avoided unless absolutely necessary.
* **Consider List Comprehension:**  If vectorization isn't possible, list comprehension can be a faster alternative to `np.vectorize()`.
* **Use `apply_along_axis()` Sparingly:**  Only when you need to apply a function to 1D slices of a multi-dimensional array.

By following these guidelines, you can write efficient NumPy code that takes advantage of its powerful vectorized operations. Remember to profile your code if performance is critical to ensure you are using the most effective method.


You're very close! The issue lies in how you're using `n.any()`.  `n.any()` checks the truthiness of the *elements of the array itself*, not the result of a comparison.  You need to apply the comparison *first*, and then use `any()` on the *resulting boolean array*.

Here's the corrected code and explanation:

```python
import numpy as np

n = np.random.randint(low=0, high=10, size=12)
n.resize(3, 4)

print(n)  # Print the array to see the values
print(n > 5)  # Print the boolean array resulting from the comparison

print((n > 5).any())  # Correct way: Apply .any() to the boolean array
print((n > 5).all()) # Correct way to check if all are true

print(n.any()) # This checks if any of the *original* numbers are non-zero.
```

**Explanation:**

1. **`n > 5`:** This creates a *new* array of the same shape as `n`, but containing boolean values (`True` or `False`).  Each element in the new array is `True` if the corresponding element in `n` is greater than 5, and `False` otherwise.  This is the boolean array you want to operate on.

2. **`(n > 5).any()`:**  This applies the `any()` method to the *boolean array* created in the previous step. It correctly checks if *at least one* element in the *boolean array* is `True` (meaning at least one element in `n` was greater than 5).

3. **`n.any()` (Incorrect):** This applies `any()` to the original array `n`.  NumPy treats any non-zero number as `True` in a boolean context. So, `n.any()` returns `True` if `n` contains any non-zero number.  This is *not* what you intended; you wanted to check if any number was greater than 5, not just if it was non-zero.

4. **`(n > 5).all()`:** This checks if all the elements in the boolean array are `True`, meaning all elements in `n` are greater than 5.

**In summary:** Always perform the comparison (e.g., `n > 5`) *first* to create a boolean array, and then apply `any()` or `all()` to that boolean array to get the desired result.
